name: Build and test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: Fabien-Chouteau/setup-ada@dev
      with:
        distrib: community
        target: native
    - uses: Fabien-Chouteau/setup-ada@dev
      with:
        distrib: community
        target: riscv32-elf
    - run: sudo apt-get install -y binutils-dev
    - run: make -C examples/simulator all test
    - run: make -C examples/embedded_simulator zfp_rv32i all test
